# Generated by Django 4.1.2 on 2022-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
