# Generated by Django 4.1.2 on 2022-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_alter_personal_data_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_data',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
